"""Async Airbnk and WeHere communication library."""

from __future__ import annotations

from .ble import AirbnkBleClient
from .cloud import AirbnkCloudClient
from .const import (
    AIRBNK_ADV_SERVICE_UUID,
    AIRBNK_CLOUD_URL,
    AIRBNK_GATT_SERVICE_UUID,
    AIRBNK_HEADERS,
    AIRBNK_LANGUAGE,
    AIRBNK_STATUS_CHARACTERISTIC_UUID,
    AIRBNK_VERSION,
    AIRBNK_WRITE_CHARACTERISTIC_UUID,
    LOCK_STATE_JAMMED,
    LOCK_STATE_LOCKED,
    LOCK_STATE_UNLOCKED,
    MANUFACTURER_ID_AIRBNK,
    OPERATION_LOCK,
    OPERATION_UNLOCK,
)
from .exceptions import (
    AirbnkBleError,
    AirbnkCloudError,
    AirbnkError,
    AirbnkProtocolError,
)
from .models import (
    AdvertisementData,
    AirbnkBleOperationResult,
    AirbnkCloudLock,
    AirbnkCloudSession,
    BatteryBreakpoint,
    BootstrapData,
    ModelProfile,
    StatusResponseData,
)
from .profiles import (
    MODEL_PROFILE_BY_KEY,
    MODEL_PROFILE_BY_MODEL,
    MODEL_PROFILES,
    SUPPORTED_MODELS,
    get_model_profile,
)
from .protocol import (
    battery_profile_from_legacy_thresholds,
    battery_profile_from_voltage_points,
    battery_profile_to_storage,
    calculate_battery_percentage,
    decrypt_bootstrap,
    describe_advert_state_bits,
    describe_status_state_nibble,
    extract_manufacturer_payload,
    generate_operation_code,
    normalize_battery_profile,
    normalize_mac_address,
    parse_advertisement_data,
    parse_status_response,
    serial_numbers_match,
    split_operation_frames,
)

__all__ = [
    "AIRBNK_ADV_SERVICE_UUID",
    "AIRBNK_CLOUD_URL",
    "AIRBNK_GATT_SERVICE_UUID",
    "AIRBNK_HEADERS",
    "AIRBNK_LANGUAGE",
    "AIRBNK_STATUS_CHARACTERISTIC_UUID",
    "AIRBNK_VERSION",
    "AIRBNK_WRITE_CHARACTERISTIC_UUID",
    "AdvertisementData",
    "AirbnkBleClient",
    "AirbnkBleError",
    "AirbnkBleOperationResult",
    "AirbnkCloudClient",
    "AirbnkCloudError",
    "AirbnkCloudLock",
    "AirbnkCloudSession",
    "AirbnkError",
    "AirbnkProtocolError",
    "BatteryBreakpoint",
    "BootstrapData",
    "LOCK_STATE_JAMMED",
    "LOCK_STATE_LOCKED",
    "LOCK_STATE_UNLOCKED",
    "MANUFACTURER_ID_AIRBNK",
    "MODEL_PROFILE_BY_KEY",
    "MODEL_PROFILE_BY_MODEL",
    "MODEL_PROFILES",
    "ModelProfile",
    "OPERATION_LOCK",
    "OPERATION_UNLOCK",
    "SUPPORTED_MODELS",
    "StatusResponseData",
    "battery_profile_from_legacy_thresholds",
    "battery_profile_from_voltage_points",
    "battery_profile_to_storage",
    "calculate_battery_percentage",
    "decrypt_bootstrap",
    "describe_advert_state_bits",
    "describe_status_state_nibble",
    "extract_manufacturer_payload",
    "generate_operation_code",
    "get_model_profile",
    "normalize_battery_profile",
    "normalize_mac_address",
    "parse_advertisement_data",
    "parse_status_response",
    "serial_numbers_match",
    "split_operation_frames",
]

__version__ = "1.0.0"
